POST localhost:8080/user
content-type:application/json

{
  "login": "Костя",
  "password": "qwerty"
}

### no correct password
GET localhost:8080/user/auth
Authorization: Basic user1 qwerty1

### correct password
GET localhost:8080/user/auth
Authorization: Basic Дмитрий1 qwerty

###
GET localhost:8080/user/1